#!/usr/bin/env sh
. "$(dirname -- "$0")/_/h"

npm run lint && \
npm run depcruise && \
npm run type-check && \
npm --workspace @phoTool/server install --no-audit --no-fund && \
npm --workspace @phoTool/shared run build && \
npm run lint:ci && \
npm run test:ci
